### ISSUE TITLE
Aeromantic Affinity trait behavior issue

### ISSUE THREAD

**Issue by Linhia** [Holic75/KingmakerFavoredClass#10]
Aeromantic Affinity does not grant the CL bonus for spells, which had their type/descriptor changed to electricity, via Elemental Bloodline Arcana - Air. 
Tested on the 2.1.5d build, using Shocking Grasp to verify that the trait functions for spells that meet the conditions by default. And by using Burning Hands to test if it works with the conversion mechanism.

**Comment by Holic75** [comment]
not a bug
