### ISSUE TITLE
Earth Element Damage Bonus not applied

### ISSUE THREAD

**Issue by FrijDom** [Holic75/KingmakerFavoredClass#9]
The dwarf favoured class option for the Kineticist to get +1/3 damage on earth element blasts that apply your Elemental Overflow bonus simply does not apply. I've tested it at both level 3 and 6, both with and without burn, and with both pure Earth and the composite Mud blasts, and with and without balance fixes. I end up with my base damage (1/2 level rounded up+constitution), plus my elemental overflow, but nothing more. From my understanding, since I've taken the bonus every level, I should have an extra +2 damage with my earth elemental blasts. This happens in version 2.15d, with only Call of the Wild, Favored Class, and Bag of Tricks for testing.

**Comment by Holic75** [comment]
Fixed in Call of the wild 1.143g
